apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal
  title: Backstage Portal
  description: StoneCo developer portal
  annotations:
    # legacy.stone.tech/owner-email: globinho@snote.com.eu
    # legacy.stone.tech/prod-date: "2023-05-10" # StoneCo-wide release date
    # tone.tech/cloud-accounts: potato,asw/stora,gcp/magali
    # grafana/dashboard-selector: DORAVENTUREIRA
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: default/some-team
  lifecycle: experimental
