apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal2
  title: Backstage Portal
  description: StoneCo developer portal
  namespace: stone
  annotations:
    legacy.stone.tech/owner-email: globinho@snote.com.eu
    legacy.stone.tech/prod-date: "2023-05-10" # StoneCo-wide release date
    stone.tech/cloud-accounts: potato,asw/stora,gcp/magali
    grafana/dashboard-selector: DORAVENTUREIRA
spec:
  type: service
  owner: eu/mario
  lifecycle: experimental
