apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal2
  title: Backstage Portal
  description: StoneCo developer portal
  namespace: stone
  annotations:
    # legacy.stone.tech/owner-email: globinho@snote.com.eu
    # legacy.stone.tech/prod-date: "2023-05-10" # StoneCo-wide release date
    # tone.tech/cloud-accounts: potato,asw/stora,gcp/magali
    # grafana/dashboard-selector: DORAVENTUREIRA
    # dev.azure.com/project: backstage-project
    # dev.azure.com/build-definition: '[app] backstage-app-CD'
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project: 'Fin-Payments'
    dev.azure.com/build-definition: 'Caju-CI'
spec:
  type: service
  owner: stone-payments/foundation-platform-experience
  lifecycle: experimental
