apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal2
  title: Backstage Portal
  description: StoneCo developer portal
  namespace: stone
spec:
  type: service
  owner: eu/mario
  lifecycle: production
