apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal2
  title: Backstage Portal
  description: StoneCo developer portal
  namespace: stone
  annotations:
    github.com/slug: miau
  links:
    - url: https://blah.com.br
      title: CD Pipeline
    - url: https://blah2.com.br
      title: Monitoring
    - url: https://blah3.com.br
      title: Incident Manager
spec:
  type: service
  owner: eu/mario
  lifecycle: experimental
