apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal2
  title: Backstage Portal
  description: StoneCo developer portal
  namespace: stone
  annotations:
    legacy.stone.tech/owner-email: globinho@snote.com.eu
    legacy.stone.tech/prod-date: "2023-05-10" # StoneCo-wide release date
    stone.tech/cloud-accounts: potato,asw/stora,gcp/magali
    grafana/dashboard-selector: DORAVENTUREIRA
    dev.azure.com/project: backstage-project
    dev.azure.com/build-definition: '[app] backstage-app-CD'
  links:
    - url: https://blah.com.br
      title: CD Pipeline
    - url: https://blah2.com.br
      title: Monitoring
    - url: https://blah3.com.br
      title: Incident Manager
spec:
  type: service
  owner: eu/mario
  lifecycle: experimental
